Add support to sanders
crdroidandroid/android_vendor_crDroidOTA pull request #181
Opened 2020-12-05 12:54 UTC by Gaituo

2020-12-05 12:54 UTC, Gaituo commented
Add initial support for Moto G(5)S Plus

2020-12-06 10:28 UTC, gwolf2u requested changes
also please include changelog_sanders.txt file

2020-12-06 10:28 UTC, gwolf2u commented on sanders.json
> +        "forum": "",
forum url is mandatory

2020-12-06 17:35 UTC, gwolf2u approved these changes

2020-12-06 17:36 UTC, merged