adopted for official
crdroidandroid/android_vendor_crDroidOTA pull request #195
Opened 2021-01-22 15:43 UTC by DhruvChhura

2021-01-22 17:34 UTC, gwolf2u requested changes
Please remove new files from initial folder
Those are not needed

2021-01-23 07:16 UTC, gwolf2u requested changes

2021-01-23 07:16 UTC, gwolf2u commented on ysl.json
> +        "size": 783 MB,
Use generated size

2021-01-23 07:16 UTC, gwolf2u commented on ysl.json
> +        "timestamp": 20210122,
Use generated timestamp

2021-01-23 07:20 UTC, DhruvChhura reviewed
Added generated timestamp and size

2021-01-23 07:22 UTC, merged