Add on7xelte Pie
crdroidandroid/android_vendor_crDroidOTA pull request #30
Opened 2018-11-04 23:53 UTC by DouglasGomes123

2018-11-05 05:01 UTC, gwolf2u requested changes

2018-11-05 05:01 UTC, gwolf2u commented on update.xml
> +        <oneplus3>
Am kind of sure Samsung doesn't have a op3 😆
```suggestion
        <on7xelte>
```

2018-11-05 10:44 UTC, ghostrider-reborn commented on update.xml
> +        <oneplus3>
such derps lol

2018-11-07 12:35 UTC, gwolf2u commented
I'll close this PR
please open a new one when corrected

2018-11-07 12:35 UTC, closed without merging