miatoll:Init CR 9.0
crdroidandroid/android_vendor_crDroidOTA pull request #377
Opened 2022-11-03 17:54 UTC by mohammadnt

2022-11-03 19:38 UTC, gwolf2u requested changes

2022-11-03 19:38 UTC, gwolf2u commented on miatoll.json
> +			"common-dt": "https://github.com/crdroidandroid/android_device_xiaomi_sm6250-common",
No 13.0 branch

2022-11-04 14:51 UTC, mohammadnt commented on miatoll.json
> +			"common-dt": "https://github.com/crdroidandroid/android_device_xiaomi_sm6250-common",
fixed

2022-11-05 16:24 UTC, gwolf2u commented on miatoll.json
> +			"common-dt": "",
no common dt now?

2022-11-05 16:38 UTC, mohammadnt commented on miatoll.json
> +			"common-dt": "",
No it does not have common dt

2022-11-06 11:48 UTC, gwolf2u approved these changes

2022-11-06 11:48 UTC, merged