Cheetah Initial 9.3 release
crdroidandroid/android_vendor_crDroidOTA pull request #425
Opened 2023-04-11 23:09 UTC by osm1019

2023-04-11 23:09 UTC, osm1019 commented
initial request for cheetah

2023-04-12 04:41 UTC, gwolf2u requested changes

2023-04-12 04:41 UTC, gwolf2u commented on changelog_cheetah.txt
> +Device: Google Pixel 7 Pro (cheetah
fix closing )

2023-04-12 04:41 UTC, gwolf2u commented on changelog_cheetah.txt
> +Device maintainer: Oscar Mariscal ()mariscal1019)
fix additional open )

2023-04-12 04:41 UTC, gwolf2u commented on changelog_cheetah.txt
> +Build type: weekly
Use capital W - "Weekly"

2023-04-12 04:41 UTC, gwolf2u commented on cheetah.json
> +			"dt": "https://github.com/osm1019/device_google_pantah",
use crDroid forks

2023-04-12 04:41 UTC, gwolf2u commented on cheetah.json
> +			"common-dt": "https://github.com/osm1019/device_google_gs201",
and here

2023-04-12 04:41 UTC, gwolf2u commented on cheetah.json
> +			"kernel": "https://github.com/osm1019/Kirisakura_Pantah"
and here

2023-04-12 04:42 UTC, osm1019 commented
ok will fix now

2023-04-12 04:54 UTC, closed without merging