Add Redmi Note 7 Pro (Violet)
crdroidandroid/android_vendor_crDroidOTA pull request #47
Opened 2019-04-15 14:02 UTC by rashedsahaji

2019-04-15 17:29 UTC, gwolf2u requested changes

2019-04-15 17:29 UTC, gwolf2u commented on update.xml
> +	    <violet>
please remove extra space from here

2019-04-15 17:29 UTC, gwolf2u commented on update.xml
> +            <filename>crDroidAndroid-9.0-20190415-violet-v5.3.zip</filename>
remove .zip from filename

2019-04-16 13:49 UTC, closed without merging

2019-04-16 13:50 UTC, rashedsahaji commented
I will create new one