OTA: adding support for Samsung Galaxy F62/M62
crdroidandroid/android_vendor_crDroidOTA pull request #470
Opened 2023-10-14 23:37 UTC by Jubscleisson

2023-10-15 16:27 UTC, gwolf2u requested changes

2023-10-15 16:27 UTC, gwolf2u commented on f62.json
> +			"forum": "",
missing forum url

2023-10-15 18:47 UTC, Jubscleisson commented on f62.json
> +			"forum": "",
Fixed, sir.

2023-10-17 17:21 UTC, gwolf2u approved these changes

2023-10-17 18:19 UTC, gwolf2u approved these changes

2023-10-17 18:20 UTC, merged