lisa: Initial Release A14 Official
crdroidandroid/android_vendor_crDroidOTA pull request #479
Opened 2023-11-12 17:31 UTC by adrian1234a

2023-11-12 18:00 UTC, gwolf2u requested changes

2023-11-12 18:00 UTC, gwolf2u commented on lisa.json
> +			"maintainer": "adrian1234a",
fix indentation

2023-11-12 18:00 UTC, gwolf2u commented on lisa.json
> +			"forum": "",
missing forum tag

2023-11-12 23:48 UTC, adrian1234a commented
now is fine?

2023-11-13 09:45 UTC, tw0xa approved these changes

2023-11-13 10:15 UTC, gwolf2u approved these changes

2023-11-13 10:16 UTC, merged

2024-01-13 23:26 UTC, nondetect commented
Is it possible to install a new build available on Sourceforge via OTA?

2024-01-13 23:27 UTC, nondetect commented
> now is fine?

Is it possible to install a new build available on Sourceforge via OTA?

2024-01-13 23:27 UTC, nondetect commented
> now is fine?

@adrian1234a  Is it possible to install a new build available on Sourceforge via OTA?