nabu : Update
crdroidandroid/android_vendor_crDroidOTA pull request #486
Opened 2023-11-20 08:29 UTC by Kfkcome

2023-11-20 15:09 UTC, gwolf2u requested changes

2023-11-20 15:09 UTC, gwolf2u commented on nabu.json
> +			"dt": "https://github.com/crdroidandroid/android_device_xiaomi_nabu",
no 14.0 branch

2023-11-20 15:09 UTC, gwolf2u commented on nabu.json
> +			"kernel": "https://github.com/crdroidandroid/android_kernel_xiaomi_nabu"
same here

2023-11-21 01:53 UTC, Kfkcome commented on nabu.json
> +			"dt": "https://github.com/crdroidandroid/android_device_xiaomi_nabu",
Sorry,I forget to sync.Now it has.

2023-11-21 01:53 UTC, Kfkcome commented on nabu.json
> +			"kernel": "https://github.com/crdroidandroid/android_kernel_xiaomi_nabu"
Already sync 14.0 branch.

2023-11-21 18:49 UTC, gwolf2u approved these changes

2023-11-21 18:49 UTC, merged