Update haydn 20231220
crdroidandroid/android_vendor_crDroidOTA pull request #524
Opened 2023-12-23 15:00 UTC by INCENDIOCODM

2023-12-23 16:54 UTC, gwolf2u requested changes

2023-12-23 16:54 UTC, gwolf2u commented on haydn_changelog.txt
> +===== 23-12-2023 =====
wrong date

2023-12-23 16:54 UTC, gwolf2u commented on haydn.json
>  			"buildtype": "Monthly",
change to beta

2023-12-24 02:04 UTC, closed without merging

2023-12-24 02:05 UTC, INCENDIOCODM commented
I will try to make a New Build ASAP
And release it on the same day