veux: Added device to OFFICIAL
crdroidandroid/android_vendor_crDroidOTA pull request #533
Opened 2023-12-24 17:46 UTC by ThePrateekBhatia

2023-12-24 18:41 UTC, gwolf2u requested changes

2023-12-24 18:41 UTC, gwolf2u commented on veux.json
> +			"oem": "Redmi/Poco",
Redmi

2023-12-24 18:41 UTC, gwolf2u commented on veux.json
> +			"device": "veux/peux",
this should be Note 11 Pro+/Poco X4 Pro

2023-12-24 18:41 UTC, gwolf2u commented on veux.json
> +			"download": "https://sourceforge.net/projects/freaky-builds/files/crDroid/crDroidAndroid-14.0-20231222-veux-v10.0.zip/",
use generated download url

2023-12-24 18:41 UTC, gwolf2u commented on veux.json
> +			"timestamp": ,
missing timestamp

2023-12-24 18:41 UTC, gwolf2u commented on veux.json
> +			"buildtype": "Stable",
Build type: Testing/Alpha/Beta/Weekly/Monthly

2023-12-24 18:41 UTC, gwolf2u commented on veux.json
> +			"gapps": "https://sourceforge.net/projects/nikgapps/files/Elite-Releases/crdroid-official/NikGapps-U/",
try official crDroid Nikgapps
https://nikgapps.com/crdroid-official

2023-12-24 18:41 UTC, gwolf2u commented on veux_changelog.txt
> +Build type: Stable
Build type: Testing/Alpha/Beta/Weekly/Monthly

2023-12-24 18:41 UTC, gwolf2u commented on veux_changelog.txt
> +Device: veux/peux
Note 11 Pro+/Poco X4 Pro

2023-12-24 19:12 UTC, ThePrateekBhatia commented
Improvements done.

2023-12-25 09:45 UTC, gwolf2u requested changes

2023-12-25 09:45 UTC, gwolf2u commented on veux.json
> +			"device": "Redmi Note 11E Pro/Note 11 Pro/Pro+/Poco X4 Pro",
Keep it to 24 chars length

2023-12-25 17:46 UTC, ThePrateekBhatia commented on veux.json
> +			"device": "Redmi Note 11E Pro/Note 11 Pro/Pro+/Poco X4 Pro",
Done

2023-12-26 09:43 UTC, gwolf2u approved these changes

2023-12-26 09:43 UTC, merged