topaz: Initial support
crdroidandroid/android_vendor_crDroidOTA pull request #572
Opened 2024-03-08 19:50 UTC by NikitaSavc

Initial support for Redmi Note 12 4G (tapas/topaz)

2024-03-08 20:05 UTC, gwolf2u requested changes

2024-03-08 20:05 UTC, gwolf2u commented on topaz.json
> +			"version": "v10.2",
remove v

2024-03-08 20:05 UTC, gwolf2u commented on topaz.json
> +			"kernel": "https://github.com/crdroidandroid/android_kernel_xiaomi_topaz"
bad url

2024-03-08 20:13 UTC, NikitaSavc commented on topaz.json
> +			"version": "v10.2",
Resolved

2024-03-08 20:14 UTC, NikitaSavc commented on topaz.json
> +			"kernel": "https://github.com/crdroidandroid/android_kernel_xiaomi_topaz"
Resolved.

2024-03-09 08:08 UTC, gwolf2u approved these changes

2024-03-09 08:08 UTC, merged