Add support for bramble + redfin
crdroidandroid/android_vendor_crDroidOTA pull request #579
Opened 2024-03-31 09:36 UTC by 306bobby-android

2024-03-31 16:39 UTC, gwolf2u requested changes

2024-03-31 16:39 UTC, gwolf2u commented on bramble.json
> +			"oem": "",
missing OEM

2024-03-31 16:39 UTC, gwolf2u commented on bramble.json
> +			"device": "",
missing device

2024-03-31 16:39 UTC, gwolf2u commented on bramble.json
> +			"download": "https://sourceforge.net/projects/crdroid/files/bramble/9.x/crDroidAndroid-13.0-20240329-bramble-v9.15.zip/download",
do upload file

2024-04-01 01:30 UTC, 306bobby-android commented
redfin, bramble, and barbet have been published to SF. DT are on org github. All is ready for confirmation

2024-04-03 18:06 UTC, gwolf2u approved these changes

2024-04-03 18:06 UTC, merged