jason: Hello to crDroid 10.x
crdroidandroid/android_vendor_crDroidOTA pull request #615
Opened 2024-05-31 15:38 UTC by iamehsangh

2024-05-31 17:24 UTC, gwolf2u requested changes

2024-05-31 17:24 UTC, gwolf2u commented on changelog_jason.txt
bad filename

2024-05-31 20:08 UTC, iamehsangh commented on changelog_jason.txt
Now i should reset commit and make a New PR?

2024-05-31 20:21 UTC, gwolf2u commented on changelog_jason.txt
just push change commit
will squash when merge

2024-06-01 14:33 UTC, gwolf2u approved these changes

2024-06-01 14:33 UTC, merged