shiba, husky, akita: initial crDroid 11
crdroidandroid/android_vendor_crDroidOTA pull request #672
Opened 2024-11-01 16:19 UTC by ionutgherman

2024-11-01 16:26 UTC, gwolf2u requested changes

2024-11-01 16:26 UTC, gwolf2u commented on akita.json
> +			"dt": "https://github.com/crdroidandroid/android_device_google_akita",
missing 15.0 branch

2024-11-01 16:26 UTC, gwolf2u commented on akita.json
> +			"common-dt": "https://github.com/crdroidandroid/android_device_google_zuma",
same here

2024-11-01 16:26 UTC, gwolf2u commented on husky.json
> +			"dt": "https://github.com/crdroidandroid/android_device_google_husky",
missing repo

2024-11-01 16:26 UTC, gwolf2u commented on husky.json
> +			"common-dt": "https://github.com/crdroidandroid/android_device_google_zuma",
15.0 ?

2024-11-01 16:26 UTC, gwolf2u commented on shiba.json
> +			"dt": "https://github.com/crdroidandroid/android_device_google_shiba",
missing repo

2024-11-01 16:26 UTC, gwolf2u commented on shiba.json
> +			"common-dt": "https://github.com/crdroidandroid/android_device_google_zuma",
15.0 ?

2024-11-02 09:10 UTC, ionutgherman commented on shiba.json
> +			"dt": "https://github.com/crdroidandroid/android_device_google_shiba",
done

2024-11-02 09:14 UTC, gwolf2u approved these changes

2024-11-02 09:14 UTC, merged

2024-12-07 19:47 UTC, Smiley-McSmiles commented
Flaahed my Pixel 8a (akita).
Couple issues so far:
1. Notifications are boxy not rounded
2. Default launcher crashes when long pressing firefox web apps (Add to homescreen) (switched to lawnchair) 

Sidenote: would love for the built in tethering options to bypass carrier restrictions. (Currently having to use the tetherfi app which uses a proxy setup to achieve this) 
Sorry I'm posting this here. I couldn't easily find a bug reporting section.