topaz: Initial topaz support for crDroid 11.x
crdroidandroid/android_vendor_crDroidOTA pull request #693
Opened 2024-11-07 09:42 UTC by mirabelle1999

2024-11-08 06:37 UTC, gwolf2u requested changes

2024-11-08 06:37 UTC, gwolf2u commented on topaz.json
> +                    "buildtype": "Monthly",
BETA

2024-11-08 06:37 UTC, gwolf2u commented on topaz.json
> +                    "forum": "",
Missing

2024-11-08 06:37 UTC, gwolf2u commented on topaz.json
> +                    "kernel": "https://github.com/crdroidandroid/android_kernel_xiaomi_topaz"
missing 15.0

2024-11-08 06:37 UTC, gwolf2u commented on topaz_changelog.txt
> +Build type: Monthly
BETA

2024-11-08 15:28 UTC, gwolf2u requested changes

2024-11-08 15:28 UTC, gwolf2u commented on topaz.json
> +                    "forum": "https://xdaforums.com/t/rom-15-official-vanilla-crdroid-for-redmi-note-12-4g.4681116/",
update forum template

2024-11-10 02:31 UTC, mirabelle1999 commented
XDA Link and trees are now updated sir

2024-11-10 06:36 UTC, gwolf2u approved these changes

2024-11-10 06:37 UTC, merged