crDroid 11.0 :Initial support panther, cheetah, lynx
crdroidandroid/android_vendor_crDroidOTA pull request #696
Opened 2024-11-08 10:12 UTC by dominator-prime

2024-11-08 14:31 UTC, gwolf2u requested changes

2024-11-08 14:31 UTC, gwolf2u commented on cheetah.json
> +			"buildtype": "Weekly",
BETA

2024-11-08 14:31 UTC, gwolf2u commented on cheetah.json
> +			"forum": "https://xdaforums.com/t/rom-cheetah-panther-14-0-crdroidandroid-v10-x.4648315/",
update forum template

2024-11-08 14:31 UTC, gwolf2u commented on cheetah.json
> +			"kernel": "https://github.com/crdroidandroid/android_kernel_google_gs201"
missing branch

2024-11-08 14:31 UTC, gwolf2u commented on cheetah_changelog.txt
> +Build type:  Weekly
BETA

2024-11-08 14:31 UTC, gwolf2u commented on lynx.json
> +			"buildtype": "Weekly",
BETA

2024-11-08 14:31 UTC, gwolf2u commented on lynx.json
> +			"forum": "https://xdaforums.com/t/rom-14-lynx-crdroid-10-25-12-2023-lynx.4647462/",
update forum template

2024-11-08 14:31 UTC, gwolf2u commented on lynx.json
> +			"kernel": "https://github.com/crdroidandroid/android_kernel_google_gs201"
missing branch

2024-11-08 14:31 UTC, gwolf2u commented on lynx_changelog.txt
> +Build type:  Weekly
BETA

2024-11-08 14:31 UTC, gwolf2u commented on panther.json
> +			"buildtype": "Weekly",
BETA

2024-11-08 14:31 UTC, gwolf2u commented on panther.json
> +			"forum": "https://xdaforums.com/t/rom-cheetah-panther-14-0-crdroidandroid-v10-x.4648315/",
update forum template

2024-11-08 14:31 UTC, gwolf2u commented on panther.json
> +			"kernel": "https://github.com/crdroidandroid/android_kernel_google_gs201"
missing branch

2024-11-08 14:31 UTC, gwolf2u commented on panther_changelog.txt
> +Build type:  Weekly
BETA

2024-11-09 05:28 UTC, dominator-prime commented on panther.json
> +			"kernel": "https://github.com/crdroidandroid/android_kernel_google_gs201"
now we are using directly from aosp-pixel source   ask Pranav for clearing your doubts

2024-11-09 05:34 UTC, closed without merging