redbull: initial cr11 update
crdroidandroid/android_vendor_crDroidOTA pull request #741
Opened 2024-11-23 02:42 UTC by 306bobby-android

2024-11-23 13:22 UTC, gwolf2u requested changes

2024-11-23 13:22 UTC, gwolf2u commented on barbet.json
> +			"buildtype": "Monthly",
BETA

2024-11-23 13:22 UTC, gwolf2u commented on barbet.json
> +			"forum": "https://xdaforums.com/t/rom-official-13-14-15-crdroid-for-pixel-5a-barbet.4646786/",
Update to new forum template

2024-11-23 13:22 UTC, gwolf2u commented on barbet_changelog.txt
> +Build type: Monthly / Stable
BETA

2024-11-23 13:22 UTC, gwolf2u commented on barbet_changelog.txt
also can update style of changelog to match others, but am ok like so also if really want to

2024-11-23 13:22 UTC, gwolf2u commented on bramble.json
> +			"buildtype": "Monthly",
BETA

2024-11-23 13:22 UTC, gwolf2u commented on bramble.json
> +			"forum": "https://xdaforums.com/t/rom-official-13-14-15-crdroid-for-pixel-4a5g-bramble.4664667/",
update forum template

2024-11-23 13:22 UTC, gwolf2u commented on bramble_changelog.txt
> +Build type: Monthly / Stable
BETA

2024-11-23 13:22 UTC, gwolf2u commented on redfin.json
> +			"buildtype": "Monthly",
BEtA

2024-11-23 13:22 UTC, gwolf2u commented on redfin.json
> +			"forum": "https://xdaforums.com/t/rom-official-13-14-15-crdroid-for-pixel-5-redfin.4664665/",
update forum template

2024-11-23 13:22 UTC, gwolf2u commented on redfin_changelog.txt
> +Build type: Monthly / Stable
BETA

2024-11-25 17:10 UTC, gwolf2u commented
inactive

2024-12-14 02:18 UTC, 306bobby-android commented
Active again, fixing right now. Template is merged on forum and will have updated files shortly with new build info and corrected build types (didn't realize monthly needed changed to beta!)

2024-12-14 02:22 UTC, 306bobby-android commented on barbet_changelog.txt
Would it be ok if I wait and rewrite changelog to new format when beta is over?

Updated old to say BETA

2024-12-14 07:07 UTC, gwolf2u commented on barbet_changelog.txt
ok with me
this status should match device.json and normal values are Testing/Alpha/Beta/Weekly/Monthly as per documentation
https://github.com/crdroidandroid/android_vendor_crDroidOTA/blob/14.0/README.md#12-changelogtxt-structure

2024-12-14 07:08 UTC, gwolf2u approved these changes

2024-12-14 07:08 UTC, gwolf2u approved these changes

2024-12-14 07:08 UTC, merged