Reinitiate Official support for rubyx
crdroidandroid/android_vendor_crDroidOTA pull request #771
Opened 2024-12-08 11:08 UTC by postcumer

2024-12-08 12:00 UTC, gwolf2u requested changes

2024-12-08 12:00 UTC, gwolf2u commented on rubyx.json
> +			"filename": "crDroidAndroid-14.0-20240915-rubyx-v10.8.zip",
this supposed to be cr11

2024-12-08 12:00 UTC, gwolf2u commented on rubyx.json
> +			"version": "11",
leave as generated

2024-12-08 12:00 UTC, gwolf2u commented on rubyx.json
> +			"forum": "https://xdaforums.com/t/temp-closed-rom-15-unofficial-crdroid-v11-beta-aosp-stable.4706860/",
fix mod edit

2024-12-08 12:00 UTC, gwolf2u commented on rubyx.json
> +			"buildtype": "Monthly",
cr11 has BETA tag

2024-12-08 12:00 UTC, gwolf2u commented on rubyx_changelog.txt
> +Build type: Monthly
BETA tag

2024-12-09 17:05 UTC, postcumer commented
Closing temporarily

2024-12-09 17:05 UTC, closed without merging