garnet: initial a15 stable released
crdroidandroid/android_vendor_crDroidOTA pull request #798
Opened 2024-12-18 18:32 UTC by JYRRC

2024-12-18 21:03 UTC, gwolf2u requested changes

2024-12-18 21:03 UTC, gwolf2u commented on garnet.json
>  			"buildtype": "BETA",
Out of beta

2024-12-18 21:03 UTC, gwolf2u commented on garnet_changelog.txt
Same here in changelog

2024-12-19 06:40 UTC, JYRRC commented on garnet_changelog.txt
ops sorry I forgot that I will fix it when I get home, thanks

2024-12-19 12:28 UTC, closed without merging