Update README.md
crdroidandroid/android_vendor_crDroidOTA pull request #84
Opened 2019-11-26 00:43 UTC by Rondeau79

2019-11-26 00:52 UTC, Rondeau79 commented
Requesting pull and write access.

2019-11-26 04:32 UTC, gwolf2u commented
You shouldn't modify the readme file
You'll need to modify update.xml and create a file changelog_device.txt
Please correct pull request

2019-11-26 04:33 UTC, gwolf2u requested changes
Needs changes

2019-11-26 05:21 UTC, Rondeau79 commented
Requested changes made.

2019-11-26 06:53 UTC, gwolf2u requested changes
also make sure to validate your XML if you are not sure how to do it 
a good online validator is this 
https://www.liquid-technologies.com/online-xml-validator

2019-11-26 06:53 UTC, gwolf2u commented on README.md
> +    <manufacturer id="Motorola">
drop changes for readme.md

2019-11-26 06:53 UTC, gwolf2u commented on update.xml
> +    	 <manufacturer id="Motorola">
manufacturer Motorola exists, don't add a new one
add your device lower in the file

2019-11-26 06:53 UTC, gwolf2u commented on update.xml
> +    </Motorola>
this needs removal

2019-11-27 04:30 UTC, Rondeau79 commented
Everything checked and lined up to the rest of the devices in the xml.

2019-11-27 08:34 UTC, closed without merging

2019-11-27 08:35 UTC, Rondeau79 commented
Revert